domain: http://localhost:${server.port}
#domain: http://192.168.1.15:${server.port}
crawler:
  task:
    enable: true
    threadPoolNum: 5
    initialDelay: 3000
    fixedRate: 300000
    cron: "*/5 * * * * ?"
  chromeDriver:
    enable: true
    linuxPath: "/hotcrawler/chromedriver"
    winPath: "D:/chromedriver-75.exe"
#--------------------------------------------
spring:
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    ssl: false
    jedis:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
logging:
  level:
    root: error
    org.springframework.web: info
    com.taogen.hotcrawler: debug
    org.hibernate: info
server:
  port: 8080