domain: https://hot.const520.com
crawler:
  task:
    enable: true
    threadPoolNum: 5
    initialDelay: 60000
    fixedRate: 300000
    cron: "*/5 * * * * ?"
  chromeDriver:
    enable: true
    linuxPath: "/hotcrawler/chromedriver"
    winPath: "D:/chromedriver-75.exe"
#--------------------------------------------
spring:
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    ssl: false
    jedis:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
logging:
  level:
    root: error
    org.springframework.web: error
    com.taogen.hotcrawler: info
    org.hibernate: error
#  path: /var/log/hot.const520.com
#  file: ${logging.path}/${spring.application.name}.log